### ISSUE TITLE
Does not work with space in path

### ISSUE THREAD

**Issue by lukasz-wronski** [felixfbecker/vscode-php-debug#10]
Hi, we are getting `source is not available` when application stops on breakpoint. We are using vs code on Windows and newest version of this plugin.

![Error](http://i.imgur.com/FFtZFfz.png)

**Comment by felixfbecker** [comment]
Hi, please try the following:
Set xdebug.remote_log in your php.ini and paste the log here
Clone this repo and try the included testproject

**Comment by lukasz-wronski** [comment]
What repo?

**Comment by felixfbecker** [comment]
This one :)

Or just download a zip file if you're not familiar with git. Alternatively, just make a very easy test.php file.

**Comment by lukasz-wronski** [comment]
This is the file we got breakpoint in: http://pastebin.com/X9xJTSVb
This is our log: http://pastebin.com/NadXVdSJ

The breakpoint was set on `phpinfo` line. We did one request with debugger turned off on and then one with debugger turned on.

**Comment by felixfbecker** [comment]
OK, this is weird. From your screenshot I can see that VS Code thinks it stopped at an inlined source ("internal module"), even though we're not. It therefor tries to do a source request, which I have not implemented, because it doesnt make sense for PHP. I think the problem is related to the space in your path, because I just checked my URI-to-path algorithm and it seems like the %20 XDebug sends is not being converted to a space. To confirm, could you please try to rename your folder and remove spaces?

**Comment by lukasz-wronski** [comment]
Bingo. Removing space fixed the problem.

**Comment by felixfbecker** [comment]
Great. I will fix this in the next version.
