### ISSUE TITLE
Not able to see all elements (level 1) of an array

### ISSUE THREAD

**Issue by luxifer** [felixfbecker/vscode-php-debug#166]
PHP version:  7.1.5
XDebug version:  v2.5.1
Adapter version:  0.2.0

Your launch.json:  

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Listen for XDebug",
            "type": "php",
            "request": "launch",
            "port": 9000,
            "serverSourceRoot": "/vagrant",
            "localSourceRoot": "${workspaceRoot}"
        }
    ]
}
```

XDebug php.ini config:  

```ini
zend_extension=xdebug.so
xdebug.var_display_max_depth = 16
xdebug.cli_color = 2
xdebug.remote_enable = 1
xdebug.remote_autostart = 1
xdebug.remote_host = 10.0.2.2
```

XDebug logfile (from setting `xdebug.remote_log` in php.ini):  None
Adapter logfile (from setting `"log": true` in launch.json):  None

Code snippet to reproduce:  No idea

When I break into some code, vscode tells me a var `$order` is an array containing 58 elements, but I don't see them all:

<img width="212" alt="capture d ecran 2017-05-23 a 10 38 07" src="https://cloud.githubusercontent.com/assets/419078/26345709/065ae8bc-3fa4-11e7-97ef-e4ef0d2f555f.png">
<img width="195" alt="capture d ecran 2017-05-23 a 10 38 20" src="https://cloud.githubusercontent.com/assets/419078/26345708/064cc6ba-3fa4-11e7-8695-601efffb7378.png">

**Comment by felixfbecker** [comment]
See xdebugSettings in the readme. This is entirely controlled through XDebug configuration.

**Comment by luxifer** [comment]
Thanks, it works. But maybe we can increase the default sent to xdebug ? Like the default value in [display](https://xdebug.org/docs/display#var_display_max_children)
IE:
```json
"xdebugSettings": {
    "max_children": 128,
    "max_data": 512,
    "max_depth": 16
}
```

**Comment by felixfbecker** [comment]
The default value is determined by XDebug. On slow machines a higher max_children causes a lot of lag, which is why I don't want to change it.

**Comment by Eddcapone** [comment]
Where do I have to add the xdebugSettings exactly?

**Comment by zobo** [comment]
Hi. In `launch.json` config. Like this:

```
{
  "configurations": [
    {
      "name": "Listen for Xdebug",
      "type": "php",
      "request": "launch",
      "port": 9003,
      "stopOnEntry": true,
      "log": true,
      "xdebugSettings": {
        "max_children": 128,
        "max_data": 512,
        "max_depth": 3
      }
    },
```

Please see the main README for details.

**Comment by MurzNN** [comment]
Thanks for the workaround! But I wonder, maybe xdebug can dynamically re-request the info about inner variable, when expanding the tree, to go deeper than `max_depth` level when needed? Or it is not possible in VS Code?

**Comment by zobo** [comment]
Hi!
The original question was about `max_children`. With this setting you can tell Xdebug to return (for example) more array elements. Typical problem, you are inspecting `$_SERVER` and are not seeing all keys. This is where `max_children` comes in.
Sadly there is currently no way in VSCode or Debug Adapter Protocol to implement a `load more...` mechanisem.

The other setting `max_depth` is something that is already implemented. When inspecting variables, each level is fetched on demand. This was however not true for the eval (Debug Console) and Watch pane because of technical details. I have changed the implementation for Eval (https://github.com/xdebug/vscode-php-debug/pull/764) and will also do for Watch in one of the next releases where this will be possible.
