### ISSUE TITLE
Still working after last updates from VSCode?

### ISSUE THREAD

**Issue by lmarcelocc** [felixfbecker/vscode-php-debug#239]
All all,

I'm asking if anyone of you are having troubles after the last Visual Studio Code updates, anyone?

Thanks.

**Comment by salixrosa** [comment]
Yes! Yesterday-day, I was using Xdebug and setting breakpoints and everything was perfectly fine.

Then I took my laptop home, and VS suggested it wanted to update, and I updated it, and... cue threeish hours trying to figure out what the problem was, and failing.

Eventually, I had to let it go. But my problem seemed to be somewhere down the chain of generating the serverFileUri for my breakpoints (I'm assuming that's what I see in my xdebug log). I could get VS to find the files for the exceptions XDebug gave it, but my xdebug log showed breakpoint file uris that were pretty much just the local mapping (rather than any kind of converted server mapping), and of course it did not break at the breakpoints.

I have no idea what the issue is, though, and don't have experiencing debugging extensions. Do you happen to know of an easy way of, say, logging things from the extension or launch.json to the VS console? I'd love proof of  what ${workspaceRoot} (or the other variants variables I tried out) actually outputs.

**Comment by patrik-martinko** [comment]
Debugging stopped working when I updated VS Code to the v1.20. I downgraded VS Code to the v1.19.3 and debugging started working properly again.

**Comment by lmarcelocc** [comment]
@salixrosa  sorry, don't know as well, how to debug the extension.

@patrik-martinko, can you share you launch.json ? Still can't get this working after downgraded to VS Code v1.19.3 :/

**Comment by salixrosa** [comment]
I didn't revert my VS Code back, but I just got it working by giving up on every variation of workspaceRoot variable and doing this:

`{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Listen for XDebug",
            "type": "php",
            "request": "launch",
            "port": 9000,
            "pathMappings": {
                "/var/www": "c:/vagrant/www"
            }
        },
    ]
}`

**Comment by lmarcelocc** [comment]
I wasn't use `workspaceRoot` variable before and my config is very similar to yours.

**Comment by salixrosa** [comment]
What're you getting for your xdebug log?

**Comment by lmarcelocc** [comment]
This is what I get when start the debugging on VS Code:
<img width="217" alt="st1" src="https://user-images.githubusercontent.com/6483007/36275999-6d9b176e-1284-11e8-8756-b39e0a1bd08e.png">


and my `xdebug.log` is completely empty and I've settled already 777 permissions (yes, I'm desperate):
<img width="387" alt="st2" src="https://user-images.githubusercontent.com/6483007/36276045-8f25d98c-1284-11e8-8cd1-12d7859de72f.png">

And this is my `launch.json`
<img width="360" alt="st3" src="https://user-images.githubusercontent.com/6483007/36276099-b7d3067a-1284-11e8-9ada-a4f074416d39.png">

**Comment by salixrosa** [comment]
Does your php_info look all right? I often do PHP --version in my command
line (in the environment where the actual PHP is running) as a quick way to
make sure XDebug is being included  at all, when I don't feel like looking
through the full info.

In my setup, if I run a php script via the command line as a user who
doesn't have the correct permission for the log file, it actually tells me
about that before running the whole thing. If you're not getting any
warnings, and you've got the file at 777 but it's empty, it sounds like
XDebug isn't running at all.

**Comment by lmarcelocc** [comment]
Yes, my phpinfo() shows that xdebug 2.6 is installed and running.

This is what's within `xdebug.log`
<img width="347" alt="st4" src="https://user-images.githubusercontent.com/6483007/36276633-73fdfda4-1286-11e8-8667-bbd0f76173af.png">

Any ideia what could be?

Thanks.

**Comment by salixrosa** [comment]
Looks like your xdebug is trying port 9100, but launch.json is listening on
9000. Changing it in launch.json might work for ya!

**Comment by lmarcelocc** [comment]
Oh, sorry for that,.

That was I trying to despite, and I've changed both on xdebug and launch.json but still nothing.

**Comment by lmarcelocc** [comment]
weird, it found the client but can't communicate with him.
<img width="589" alt="st1" src="https://user-images.githubusercontent.com/6483007/36276934-45bdd152-1287-11e8-9f39-8b6616ef5791.png">

**Comment by lmarcelocc** [comment]
Ok, found the problem!!

Windows firewal was blocking!!

Thank you @salixrosa  for you precious help1

**Comment by salixrosa** [comment]
Yay :D Happy debugging!

**Comment by LostBeard** [comment]
Not working for me after updating VS Code. VSC would not stop on any of my breakpoints, but would stop on exceptions if I checked the box for it. I tried changing my path mapping to use the path directly instead of what was working before the update ("${workspaceRoot}/") and that did not help. Reverted to 1.19.3 and VSC is now stopping on my breakpoints again.

If anyone else needs it until this is figured out.
https://vscode.cdn.azure.cn/stable/7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba/VSCodeSetup-x64-1.19.3.exe

**Comment by felixfbecker** [comment]
Well if it was broken for everyone because of a vscode update, it seems like this is an issue with that update. Maybe they removed `${workspaceRoot}` and it is now `${workspaceFolder}`?

**Comment by patrik-martinko** [comment]
It doesn't work with `${workspaceFolder}` either (even with absolute path). Xdebug on the server logs communication correctly but VS Code v1.20 doesn't stop at breakpoints. It works with VS Code 1.19.

**Comment by patrik-martinko** [comment]
But I noticed that VS Code v1.20 breaks on exceptions though.

**Comment by lmarcelocc** [comment]
Hi all,

I've also tried with `${workspaceFolder} `but no success.

Thanks.

**Comment by Metrakit** [comment]
same issue for me since last vscode update

**Comment by opus-2** [comment]
Same issue for me too. I have fixed it by replacing "{$workspaceRoot}" with absolute path BUT NOTICE **THE DRIVE LETTER MUST BE LOWER CASE** for it to work.
I lost 2 days of work because of this screw up on 1.20. Needless to say, I'm calling vscode developers a million creative names. And their mothers.

**Comment by felixfbecker** [comment]
@opus-2 please self-moderate your comment or I will delete it. Your attitude is extremely disrespectful.

**Comment by opus-2** [comment]
Please tell me what exactly is "extremely disrepectful" in that comment.

**Comment by AdamBassett** [comment]
Was a solution ever found for this?  I just updated my vscode yesterday and I'm getting the same behavior.  xDebug for PHP stops on exceptions but wont stop on any brake points. It was working yesterday before I updated, now nothing.  I have a project due Monday I need to find a fix ASAP.

**Comment by lmarcelocc** [comment]
@AdamBassett , go back for an older version of VS code, it's the quick fix.

**Comment by AdamBassett** [comment]
Ok how do I do that I cant find a download for 1.19

**Comment by lmarcelocc** [comment]
[https://vscode.cdn.azure.cn/stable/7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba/VSCodeSetup-x64-1.19.3.exe](url)

**Comment by AdamBassett** [comment]
Thanks now that you that link I see is posted above.  I missed it before thanks!

**Comment by rulatir** [comment]
Can't believe an issue like this eventually gets resolved with "use an older version"...

**Comment by felixfbecker** [comment]
@rulatir it was fixed in https://github.com/felixfbecker/vscode-php-debug/commit/26177956dee82824b7e4d3a51de9009a44e3bc14
