### ISSUE TITLE
[v-test][PHP] Debug add to watch doesn't show value of array item

### ISSUE THREAD

**Issue by weinand** [felixfbecker/vscode-php-debug#26]
_From @vsccarl on March 11, 2016 19:8_

OS: Windows 10
Build#: 0.10.12-alpha
Node: 4.1.1

When adding a single array element to the watch list, it doesn't correctly show the value of the element.
Adding the entire array to the watch list works as expected.

Example:
![phpaddtowatcharrayfoo](https://cloud.githubusercontent.com/assets/12900364/13712617/845f6c9e-e779-11e5-9825-1d677bb88a95.JPG)

_Copied from original issue: Microsoft/vscode#4029_

**Comment by weinand** [comment]
_From @felixfbecker on March 12, 2016 10:42_

Afaik VS Code doesn't include a PHP debugger, so in case you are using my extension, you might want to move the issue to https://github.com/felixfbecker/vscode-php-debug

**Comment by felixfbecker** [comment]
That's because `$array.foo` is not valid syntax for array access:
![image](https://cloud.githubusercontent.com/assets/10532611/13738689/f971ca0a-e9c6-11e5-8d91-d148f53000ba.png)

The correct syntax is `$array['foo']`. When you execute `$array.foo`, the dot acts as a string concatenation operator (the same as `$array . foo`). PHP will convert `$array` to a string, which results in `Array`. It will then concatenate that with `foo`, and since `foo` is not a defined constant, it will implicitly assume you meant `"foo"` and convert it to a string, resulting in `Arrayfoo`.
